cloud:
  aws:
    credentials:
      access-key: AWS_ACCESS_KEY
      secret-key: AWS_SECRET_ACCESS_KEY
    region:
      static: us-east-2
      auto: false

application:
  bucket:
    name: spring-amazon-myimg

server:
  port: 8080


