cloud:
  aws:
    credentials:
      access-key: AKIAZFITJ6BPDDPMKWG6
      secret-key: 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
    region:
      static: us-east-2
      auto: false

application:
  bucket:
    name: spring-amazon-myimg

server:
  port: 8080


