package com.dampcave.courseworkitransitionai.models;

public enum Genre {
    COMEDY,FAMILY,MELODRAMA,DRAMA,THRILLER,HORRORS,ACTION,WESTERN,MILITARY,CRIME,DETECTIVE,NOIR,
    HISTORY,BIOGRAPHY,SPORT,ADVENTURES,FANTASTIC,FANTASY,CARTOON,ANIME,CHILDLIKE,MUSIC,MUSICAL

}
